on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  approval-gate:
    name: "Approval gate"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - run: echo "Received approval. Moving on to next job..."

  build:
    name: "Build"
    needs: approval-gate
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.BUILD_SECRET }}

  deploy:
    name: "Deploy"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.DEPLOY_SECRET }}
