on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  approval-gate:
    name: "Approval gate"
    runs-on: ubuntu-latest
    environment: approval
    steps:
      - run: echo "Received approval. Moving on to next job..."

  build:
    name: "Build"
    needs: approval-gate
    environment: ${{ github.event.input.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.BUILD_SECRET }}" | base64

  deploy:
    name: "Deploy"
    needs: build
    environment: ${{ github.event.input.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.DEPLOY_SECRET }}" | base64
